version: '3'
services:
  db:
    image: postgres
    volumes:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  web:
    build: .
    command: bash -c "rake db:setup && rails server --port 3000 --binding 0.0.0.0"
    ports:
      - "3000:3000"
    depends_on:
      - db
    links:
      - db
